#!/bin/sh

export YoukuHome="/tmp/youku"

old=$(cat /tmp/youkudome.pid)
echo $$ >/tmp/youkudome.pid
[ "$old" ] && kill -9 $old > /dev/null 2>&1

bootup() {
	[ -d "$YoukuHome" ] && return 0;
	mkdir -p $YoukuHome
	mkdir -p $YoukuHome/ipk
	mkdir -p $YoukuHome/bin
	mkdir -p $YoukuHome/data
	return 0
}

optimize() {
	local data="\
linux-vm-max-cpu-busy-linger=10&\
linux-vm-max-net-upload-k-speed=2000&\
linux-vm-max-net-download-k-speed=2000&\
upload-limit-model=0&\
pcdn-work-mode=0&\
upload-max-uploading-count=2000&\
upload-max-waiting-count=80&\
pcdn-radic-max-download-size-per-hour=8294967296&\
pcdn-radic-max-remove-size-per-hour=8294967296&\
peak-period=07:00-24:00&\
download-disable-in-peak-period=0&\
enable-flash-p2p-hint=1&\
max-cache-buffer-size=24&\
";
	curl --connect-timeout 2 --data "${data}" "http://127.0.0.1:8908/peer/config/xml?m=put"
	return 0
}
local ikuacc="ikuacc"
path=$(uci get -q youku.@path[0].path)
[ -d "$path" ] || return 0;
bootup
if [ "$path" = "" ]
then
	killall -9 ikuacc
	exit 0
fi

[ -e $path/ikuacc ]||mkdir -p $path/ikuacc
[ -d "$path/meta" ]||mkdir -p $path/meta
ln -sfn $path/meta $YoukuHome

if [ "$(uci get -q youku.youku.enable)" = "0" ]
then
	[ "$(cat /etc/crontabs/root|grep /lib/youku/youku)" ] && sed -i 's/\*\/5 \* \* \* \* sh \/lib\/youku\/youku > \/dev\/null 2>&1//g' /etc/crontabs/root
	[ "$(cat /etc/crontabs/root|grep /lib/today)" ] && sed -i 's/20 \*\/1 \* \* \* sh \/lib\/today > \/dev\/null 2>&1//g' /etc/crontabs/root
	[ "$(cat /etc/firewall.user|grep "tcp --dport 4466")" ] && sed -i 's/iptables \-I INPUT \-p tcp \-\-dport 4466 \-j ACCEPT//g' /etc/firewall.user
	[ "$(cat /etc/firewall.user|grep "udp --dport 4466")" ] && sed -i 's/iptables \-I INPUT \-p udp \-\-dport 4466 \-j ACCEPT//g' /etc/firewall.user
	[ "$(cat /etc/firewall.user|grep "input_wan_rule -p udp")" ] && sed -i 's/iptables \-I input_wan_rule \-p udp \-j ACCEPT//g' /etc/firewall.user
	killall -9 ikuacc
	exit 0
else
	[ "$(cat /etc/crontabs/root|grep /lib/youku/youku)" ] || echo "*/5 * * * * sh /lib/youku/youku > /dev/null 2>&1">>/etc/crontabs/root	#每5分钟检测程序是否运行
	[ "$(cat /etc/crontabs/root|grep /lib/today)" ] || echo "20 */1 * * * sh /lib/today > /dev/null 2>&1">>/etc/crontabs/root
	[ "$(cat /etc/firewall.user|grep "tcp --dport 4466")" ] || echo "iptables -I INPUT -p tcp --dport 4466 -j ACCEPT">>/etc/firewall.user
	[ "$(cat /etc/firewall.user|grep "udp --dport 4466")" ] || echo "iptables -I INPUT -p udp --dport 4466 -j ACCEPT">>/etc/firewall.user
	[ "$(cat /etc/firewall.user|grep "input_wan_rule -p udp")" ] || echo "iptables -I input_wan_rule -p udp -j ACCEPT">>/etc/firewall.user
fi

VERSION=$(uci get -q youku.youku.VERSION)
url=$(grep "\<$VERSION\>" /lib/youku/FILES|awk '{print$3}')
md6=$(grep "\<$VERSION\>" /lib/youku/FILES|awk '{print$2}')
if [ ! -z "$VERSION" ]; then
	if [ ! -e $path/ikuacc/ikuacc.${VERSION} ] ;then
		while [ "$md5" != "$md6" ] #比对MD5.
		do
		wget -qO /tmp/youku/ipk/youku.ipk -T 120 -t 10 --no-check-certificate ${url}
		tar zxvf /tmp/youku/ipk/youku.ipk -C /tmp/youku/ipk
		tar zxvf /tmp/youku/ipk/data.tar.gz -C /tmp/youku/ipk
		cp $(find /tmp/youku/ipk/ -name "ikuacc") $path/ikuacc/ikuacc.${VERSION}

		md5=$(md5sum $path/ikuacc/ikuacc.${VERSION}|awk '{print$1}')
		sleep 1
			rm -rf /tmp/youku/ipk/*
	 	done
	chmod 755 $path/ikuacc/ikuacc.${VERSION}
 	uci set youku.youku.VERSION=${VERSION}
 	uci commit youku
	fi
cp $path/ikuacc/ikuacc.$VERSION $YoukuHome/bin/ikuacc
ikuacc="$YoukuHome/bin/ikuacc"
fi
sleep 1
wksn="$(uci get -q youku.youku.opsn)"
str="--device-serial-number="0000$wksn" --mobile-meta-path="$YoukuHome/meta" --mobile-data-path="
i=0
while [ "$(uci get -q youku.@path[$i].path)" != "" ]
do
partsize=`df -m | grep $(uci get -q youku.@path[$i].path) | awk '{print $2 }'`
[ ${partsize} -gt 500 ] && {
	if [ $(uci get -q youku.@path[$i].pathhc) != "" ]
	then
		hc=":$(uci get -q youku.@path[$i].pathhc)"
	else
		hc=""
	fi
	[ -d "$path/youku" ]||mkdir -p $path/youku
	path=$(uci get -q youku.@path[$i].path)
	if [ -d $path/youku/data ] ;then	#兼容官方缓存
		ln -sfn $path/youku/data $YoukuHome/data/data$i
	else
		ln -sfn $path $YoukuHome/data/data$i
	fi
		str="$str$YoukuHome/data/data$i$hc;"
	i=$(($i+1))
}
done
sdt="0"
while true
do
	sleep 1
	if [ "$(uci get -q youku.youku.cqboot)" = "$(date +%H%M)" ]
	then
		sleep 30
		if [ "$(uci get -q youku.youku.ikrebot)" = "1" ]
		then
			killall ikuacc
			sleep 3
		else
			reboot
		fi
	fi
	sleep 5

	if [ "$(uci get -q youku.youku.enable)" = "1" ]
	then
		if [ "$(pidof ikuacc)" = "" ]
		then
			sleep 5
			$ikuacc ${str%?} &
			sleep 20
			optimize
			sdt="1"
		fi
	fi
	if [ "$sdt" = "1" ]
	then
		wget -O - 'http://127.0.0.1:8908/peer/limit/network/set?upload_model='"$(uci get -q youku.youku.wkmod)" > /dev/null 2>&1
		sleep 2
		sdt="0"
	fi
	if [ "$(uci get -q youku.youku.enable)" = "0" ]
	then
		killall -9 ikuacc
		exit 0
	fi
	sleep 30
done
