#!/bin/sh /etc/rc.common

START=99

start(){
	killall -9 ikuacc youku-main
	sleep 1
	/etc/youku/youku-main &
}

stop(){
	killall -9 ikuacc youku-main
}

restart(){
	killall -9 ikuacc youku-main
	sleep 1
	/etc/youku/youku-main &
}
